--멤버테이블 생성
CREATE TABLE tbl_member(
 ID VARCHAR2(15) PRIMARY KEY
 , PASSWORD VARCHAR2(30) NOT NULL
 , NAME VARCHAR2(100) NOT NULL
 , BIRTHDAY VARCHAR2(50) NOT NULL
 , PHONE_NUMBER VARCHAR(50) NOT NULL
 , REG_DATE DATE DEFAULT SYSDATE
);
COMMIT;
--시퀀스 추가
CREATE SEQUENCE seq_tbl_email_no
       INCREMENT BY 1 
       START WITH 1
       NOCACHE;
COMMIT;
--이메일 테이블 생성
CREATE TABLE tbl_email(
 NO number(5) PRIMARY KEY
 ,WRITER VARCHAR2(30) NOT NULL
 ,RECEIVER VARCHAR2(30) NOT NULL
 ,REG_DATE DATE DEFAULT SYSDATE
 ,TITLE VARCHAR2(1000) NOT NULL
 ,EMAIL_BODY VARCHAR2(4000) NOT NULL
 ,ID VARCHAR2(15) NOT NULL
 ,CONSTRAINT FK_EMAIL FOREIGN KEY (RECEIVER)
 REFERENCES TBL_MEMBER(ID)
);
COMMIT;
--이메테이블 구조 복사 -> trash 테이블 생성
CREATE TABLE TBL_TRASH AS SELECT * FROM TBL_EMAIL WHERE 1=2;
COMMIT;

ALTER TABLE TBL_TRASH 
ADD CONSTRAINTs FK_TRASH FOREIGN KEY (RECEIVER)
REFERENCES TBL_MEMBER(ID);
COMMIT;

--데이터 추가
--멤버 데이터 입력, 나머진 회원가입으로 입력
INSERT INTO TBL_MEMBER(ID,PASSWORD,NAME,BIRTHDAY,PHONE_NUMBER)
 VALUES('park', 'park1234', '박길동', '010312', '010-6645-2123');

INSERT INTO TBL_MEMBER(ID,PASSWORD,NAME,BIRTHDAY,PHONE_NUMBER)
 VALUES('ju', 'ju1234', '주상혁', '970930', '010-1111-1213');

INSERT INTO TBL_MEMBER(ID,PASSWORD,NAME,BIRTHDAY,PHONE_NUMBER)
 VALUES('kang', 'kang1234', '강소연', '740824', '010-2222-2222');

INSERT INTO TBL_MEMBER(ID,PASSWORD,NAME,BIRTHDAY,PHONE_NUMBER)
 VALUES('hansung', 'hansung12', '한성컴퓨터', '700824', '010-8282-8282');

INSERT INTO TBL_MEMBER(ID,PASSWORD,NAME,BIRTHDAY,PHONE_NUMBER)
 VALUES('hong', 'hong1234', '홍길동', '650824', '010-1879-1578');

INSERT INTO TBL_MEMBER(ID,PASSWORD,NAME,BIRTHDAY,PHONE_NUMBER)
 VALUES('gu', 'gu1234', '구준표', '911105', '010-4446-7777');

INSERT INTO TBL_MEMBER(ID,PASSWORD,NAME,BIRTHDAY,PHONE_NUMBER)
 VALUES('han', 'han0012', '한성욱', '891016', '010-4876-0156');

INSERT INTO TBL_MEMBER(ID,PASSWORD,NAME,BIRTHDAY,PHONE_NUMBER)
 VALUES('wang', 'wang01', '왕서방', '680202', '010-7979-8514');
INSERT INTO TBL_MEMBER(ID,PASSWORD,NAME,BIRTHDAY,PHONE_NUMBER)
 VALUES('hansuk', 'hansuk', '한석원', '650822', '010-9642-7015');

-- 메일데이터 입력
INSERT  INTO TBL_EMAIL (NO, WRITER ,RECEIVER, TITLE, EMAIL_BODY, ID)
 VALUES(seq_TBL_EMAIL_no.nextval, 'park', 'gu', 'Hello11', 'b1111111111eqadsadasd', 'kang');

INSERT  INTO TBL_EMAIL (NO, WRITER ,RECEIVER, TITLE, EMAIL_BODY, ID)
 VALUES(seq_TBL_EMAIL_no.nextval, 'hansung', 'kang', '1541콜랙트콜', 'bbbbbbweraxzczxeqc', 'han');

INSERT  INTO TBL_EMAIL (NO, WRITER ,RECEIVER, TITLE, EMAIL_BODY, ID)
 VALUES(seq_TBL_EMAIL_no.nextval, 'gu', 'kang', 'ㅎㅇㅇ', '잘부탁드립니다.', 'hong');

INSERT  INTO TBL_EMAIL (NO, WRITER ,RECEIVER, TITLE, EMAIL_BODY, ID)
 VALUES(seq_TBL_EMAIL_no.nextval, 'hansuk', 'wang', '시공의폭풍 지금 접...', '시공의 폭풍은 정말 최고야!', 'park');

INSERT  INTO TBL_EMAIL(NO, WRITER ,RECEIVER, TITLE, EMAIL_BODY, ID)
 VALUES(seq_TBL_EMAIL_no.nextval, 'ju', 'hansung', '야인시대', '스타크래프트 1.16.1립버전 다운...[더보기]', 'hong');

INSERT  INTO TBL_EMAIL(NO, WRITER ,RECEIVER, TITLE, EMAIL_BODY, ID)
 VALUES(seq_TBL_EMAIL_no.nextval, 'gu', 'wang', '제품이 할인중입니다.', '찜목록에 있는 제품이 할인중입니다.', 'gu');

INSERT  INTO TBL_EMAIL(NO, WRITER ,RECEIVER, TITLE, EMAIL_BODY, ID)
 VALUES(seq_TBL_EMAIL_no.nextval, 'han', 'gu', 'hi gu', 'eqwewqewqeqweqasf', 'han');

INSERT  INTO TBL_EMAIL(NO, WRITER ,RECEIVER, TITLE, EMAIL_BODY, ID)
 VALUES(seq_TBL_EMAIL_no.nextval, 'han', 'park', '라면10세트 할인중', '신라면, 진라면 등 각종라면 파격세일!!!', 'han');

INSERT  INTO TBL_EMAIL(NO, WRITER ,RECEIVER, TITLE, EMAIL_BODY, ID)
 VALUES(seq_TBL_EMAIL_no.nextval, 'han', 'gu', '24/04/22 회의내용', '회장님... 부장님... 과장님...', 'han');

COMMIT;

--데이터 복사(휴지통)
INSERT INTO TBL_TRASH  
SELECT * FROM TBL_EMAIL WHERE RECEIVER = 'gu' OR WRITER = 'gu';
COMMIT;

